# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  cypress: cypress-io/cypress@1
  
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:chrome69'

    working_directory: ~/sec-crawl/sec-crawl-react

jobs:
  build_server:
    docker:
      - image: circleci/python:3.7.1

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            sudo pip install pytest
            python -m pytest

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

workflows:
  build:
    jobs:
      - build_server
      - cypress/run:
          record: true
          executor: with-chrome
