# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  build_server:
    docker:
      - image: circleci/python:3.7.1

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install pytest
            python -m pytest

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

workflows:
  build:
    jobs:
      - build_server
      - cypress/install:
          build: 'cd sec-crawl-react && npm run build'
      - cypress/run:
          record: true
          start: 'cd sec-crawl-react && npm start'
