# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.5.0
jobs:
  build_server:
    docker:
      - image: circleci/python:3.7.1
      - image: circleci/mongo:4.0.3

    working_directory: ~/seccrawl

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  build_client:    
    working_directory: ~/seccrawl/sec-crawl-react
    steps:
      - cypress/run:
           start: 'npm start'
           record: true