version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "sec-crawl-react/package.json" }}
            - v2-deps-{{ .Branch }}
            - v2-deps
      - run:
          name: Install Dependencies
          command: cd sec-crawl-react && npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "sec-crawl-react/package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run: sec-crawl-react/node_modules/.bin/cypress run
