version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "sec-crawl-react/package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: cd sec-crawl-react && npm run build
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "sec-crawl-react/package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run: sec-crawl-react/node_modules/.bin/cypress run
